version: '3.8'

services:
  # Nginx Proxy Manager
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - npm-data:/data
      - npm-letsencrypt:/etc/letsencrypt

  # Portainer - Gestionnaire de conteneurs Docker
  portainer:
    image: 'portainer/portainer-ce:latest'
    restart: always
    ports:
      - '9000:9000' # Interface Web Portainer
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - portainer-data:/data

  # Base de données pour Nextcloud
  db:
    image: 'mariadb:latest'
    command: --transaction-isolation=READ-COMMITED --binlog-format=ROW
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Pavel180400&SrvPortair@QEIHUSR6U9IP
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: PavelAdmin
      MYSQL_PASSWORD: Pavel180400&SrevPortair@QEIHUSR6U9IP
    networks:
      - nextcloud-net

  # Nextcloud
  nextcloud:
    depends_on:
      - db
    image: 'nextcloud:latest'
    restart: always
    volumes:
      - nextcloud-data:/var/www/html
    environment:
      MYSQL_HOST: db
      MYSQL_PASSWORD: Pavel180400&SrvPortair@QEIHUSR6U9IP
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: PavelAdmin
    networks:
      - nextcloud-net

networks:
  nextcloud-net:
    driver: bridge

volumes:
  npm-data:
  npm-letsencrypt:
  portainer-data:
  db-data:
  nextcloud-data: