version: "3.8"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - '443:443'
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt

  db_nginx_proxy:
    image: jc21/mariadb-aria
    environment:
      MYSQL_ROOT_PASSWORD: Pavel180400&Nextcloud@QEIHUSR6U9IP
      MYSQL_DATABASE: nginx_proxy_manager
      MYSQL_USER: PavelAdmin
      MYSQL_PASSWORD: Pavel180400&Nextcloud@QEIHUSR6U9IP
    volumes:
      - npm_db:/var/lib/mysql

  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    restart: always
    environment:
      - VIRTUAL_HOST=portainer.delhomme.ovh
      - VIRTUAL_PORT=9000
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - portainer_data:/data

volumes:
  portainer_data:
  npm_data:
  npm_db:
  npm_letsencrypt: