version: '3'

volumes:
  nextcloud-data:
  nextcloud-db:

networks:
  frontend:
  backend:

services:
  nextcloud-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - nextcloud-data:/var/www/html
    environment:
      - MYSQL_PASSWORD=Pavel180400&Nextcloud@QEIHUSR6U9IP
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=PavelAdmin
      - MYSQL_HOST=nextcloud-db
      - PHP_UPLOAD_LIMIT=300G
    networks:
      - frontend
      - backend

  nextcloud-db:
    image: mariadb:latest
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITED --binlog-format=ROW
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Pavel180400&Nextcloud@QEIHUSR6U9IP
      - MYSQL_PASSWORD=Pavel180400&Nextcloud@QEIHUSR6U9IP
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=PavelAdmin
      - OVERWRITEPROTOCOL=https
    networks:
      - backend

  onlyoffice:
    image: onlyoffice/documentserver
    expose:
      - '80'
    volumes:
      - document_data:/var/www/html/onlyoffice/Data
      - document_log:/var/log/onlyoffice
      - document_lib:/var/lib/onlyoffice
    networks:
      - backend