version: '3'

services:
  # Nginx Proxy Manager
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - '/data/nginx-proxy-manager:/data'
      - '/data/nginx-proxy-manager/letsencrypt:/etc/letsencrypt'
